CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time TIMESTAMP NOT NULL,
    content TEXT NOT NULL,
    source VARCHAR(255) NOT NULL,
    sender VARCHAR(255) NOT NULL
);